import re
import pathlib

b = pathlib.Path(r"D:\yugen-eos\third_party\eos_sdk\SDK\Include")
T = {f.name: f.read_text(errors="replace") for f in b.glob("*.h")}
A = "\n".join(T.values())

print("--- ContinuanceToken funcs ---")
for m in sorted(set(re.findall(r"EOS_\w*ContinuanceToken\w*", A))):
    print("   ", m)
i = A.find("EOS_PlayerDataStorage_WriteFile")
print("--- WriteFile decl ctx ---")
print(A[i - 700:i + 300])
i = A.find("EOS_PlayerDataStorage_ReadFile")
print("--- ReadFile decl ctx ---")
print(A[i - 700:i + 300])
i = A.find("EOS_TitleStorage_ReadFile")
print("--- TS ReadFile decl ctx ---")
print(A[i - 700:i + 300])
i = A.find("EOS_DECLARE_CALLBACK(EOS_PlayerDataStorage_OnWriteFileDataCallback")
print("--- WriteData typedef ---")
print(A[i:i + 600] if i >= 0 else "NOT FOUND")
i = A.find("EOS_PlayerDataStorage_EReadResult")
print("--- EReadResult ---")
print(A[i - 300:i + 700] if i >= 0 else "NOT FOUND")
i = A.find("EOS_DECLARE_CALLBACK(EOS_PlayerDataStorage_OnReadFileCompleteCallback")
print("--- ReadComplete typedef ---")
print(A[i:i + 400] if i >= 0 else "NOT FOUND")
i = A.find("EOS_DECLARE_CALLBACK(EOS_PlayerDataStorage_OnWriteFileCompleteCallback")
print("--- WriteComplete typedef ---")
print(A[i:i + 400] if i >= 0 else "NOT FOUND")
i = A.find("EOS_DECLARE_CALLBACK(EOS_PlayerDataStorage_OnFileTransferProgressCallback")
print("--- Progress typedef ---")
print(A[i:i + 400] if i >= 0 else "NOT FOUND")
i = A.find("EOS_TitleStorage_OnReadFileDataCallback")
print("--- TS ReadData typedef ---")
print(A[i - 200:i + 500] if i >= 0 else "NOT FOUND")
i = A.find("FileTransferRequest_Release")
print("--- FTR Release ---")
print(A[i - 400:i + 200])
