import re
import pathlib

b = pathlib.Path(r"D:\yugen-eos\third_party\eos_sdk\SDK\Include")
T = {f.name: f.read_text(errors="replace") for f in b.glob("*.h")}
A = "\n".join(T.values())

def grab(marker, length=600):
    i = A.find(marker)
    print("--- " + marker + " ---")
    print(A[i:i + length] if i >= 0 else "NOT FOUND")

i = A.find("EOS_ENUM(EOS_ESessionAttributeType")
print("--- attr type enum ---")
print(A[i:i + 500])
i = A.find("EOS_ENUM(EOS_ESessionAttributeAdvertisementType")
print("--- attr advert enum ---")
print(A[i:i + 400])
grab("EOS_RTCAudio_UpdateSendingVolume(EOS_HRTCAudio")
grab("EOS_RTCAudio_UpdateReceivingVolume(EOS_HRTCAudio")
i = A.find("EOS_STRUCT(EOS_Sanctions_PlayerSanction")
print("--- PlayerSanction ---")
print(A[i:i + 800] if i >= 0 else "NOT FOUND")
i = A.find("EOS_STRUCT(EOS_Lobby_Attribute")
print("--- Lobby_Attribute ---")
print(A[i:i + 700] if i >= 0 else "NOT FOUND")
grab("EOS_Lobby_CreateLobbySearch(EOS_HLobby")
grab("EOS_LobbySearch_Find(EOS_HLobbySearch")
grab("EOS_LobbySearch_CopySearchResultByIndex(EOS_HLobbySearch")
grab("EOS_LobbySearch_GetSearchResultCount(")
grab("EOS_Achievements_QueryDefinitions(EOS_HAchievements")
grab("EOS_Achievements_GetAchievementDefinitionCount(")
grab("EOS_Mods_EnumerateMods(EOS_HMods")
grab("EOS_KWS_QueryAgeGate(EOS_HKWS")
grab("EOS_ProgressionSnapshot_BeginSnapshot(")
grab("EOS_ProgressionSnapshot_AddProgression(")
grab("EOS_ProgressionSnapshot_SubmitSnapshot(")
grab("EOS_ProgressionSnapshot_EndSnapshot(")
i = A.find("EOS_STRUCT(EOS_Platform_RTCOptions")
print("--- RTCOptions ---")
print(A[i:i + 900] if i >= 0 else "NOT FOUND")
i = A.find("IntegratedPlatformOptionsContainerHandle")
print("--- integrated handle in options ---")
print(A[i - 300:i + 200] if i >= 0 else "NOT FOUND")
grab("EOS_UI_IsSocialOverlayPaused(EOS_HUI")
grab("EOS_UI_GetNotificationLocationPreference(")
grab("EOS_SessionDetails_GetSessionAttributeCount(")
