#pragma once

#define YUGEN_EOS_WRAPPER_VERSION_MAJOR 0
#define YUGEN_EOS_WRAPPER_VERSION_MINOR 1
#define YUGEN_EOS_WRAPPER_VERSION_PATCH 0
#define YUGEN_EOS_SDK_MAJOR 1
#define YUGEN_EOS_SDK_MINOR 19
#define YUGEN_EOS_SDK_PATCH 1
#define YUGEN_EOS_SDK_HOTFIX 2
#define YUGEN_EOS_GODOT_MINIMUM "4.3"
